FROM guergeiro/pnpm:18-7 as cache
WORKDIR /usr/src/app
COPY pnpm-lock.yaml .
RUN pnpm fetch
ADD . ./
RUN pnpm install --offline
RUN rm -rdf backend
RUN rm -rdf tools
WORKDIR /usr/src/app/frontend
CMD pnpm dev
