FROM guergeiro/pnpm:18-8 as cache
WORKDIR /usr/src/app
COPY pnpm-lock.yaml .
RUN pnpm fetch
COPY . ./
RUN pnpm install --prefer-offline --recursive --shamefully-hoist
RUN rm -rdf backend
RUN rm -rdf tools
WORKDIR /usr/src/app/frontend
CMD pnpm dev
