FROM guergeiro/pnpm:18-8 as production
WORKDIR /usr/src/app
COPY . .
RUN pnpm install --prod
RUN rm -rdf backend
RUN rm -rdf tools

FROM gcr.io/distroless/nodejs:18
WORKDIR /usr/src/app
COPY --from=production /usr/src/app .

WORKDIR /usr/src/app/frontend
CMD ["dist/server/entry.mjs"]
