version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    container_name: mesw-breno-salles_redis
    restart: always
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: mesw-breno-salles_backend
    restart: always
    environment:
      PORT: 50000
    volumes:
      - ./backend/src:/usr/src/app/backend/src
    ports:
      - "3000:50000"
  miguel-brito:
    build:
      context: .
      dockerfile: tools/miguel-brito/Dockerfile.dev
    container_name: mesw-breno-salles_miguel-brito
    restart: always
    volumes:
      - ./tools/miguel-brito/src:/usr/src/app/tools/miguel-brito/src
