version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
  broker:
    image: redis
    container_name: mesw-breno-salles_broker
    restart: always
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: mesw-breno-salles_backend
    restart: always
    environment:
      POSTGRES_URI: postgres://app_user:password@postgres:5432/app_db
      PORT: 50000
      REDIS_HOST: broker
      REDIS_PORT: 6379
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/temp
      - /usr/src/app/backend/node_modules

      - ./shared:/usr/src/app/shared
      - /usr/src/app/shared/nestjs/node_modules
      - /usr/src/app/shared/tools/node_modules
    ports:
      - "3000:50000"
  tool-queue:
    image: redis
    container_name: mesw-breno-salles_tool-queue
    restart: always
  miguel-brito:
    build:
      context: .
      dockerfile: tools/miguel-brito/Dockerfile.dev
    container_name: mesw-breno-salles_miguel-brito
    restart: always
    environment:
      REDIS_HOST: broker
      REDIS_PORT: 6379
      QUEUE_HOST: tool-queue
      QUEUE_PORT: 6379
    volumes:
      - ./tools/miguel-brito/src:/usr/src/app/tools/miguel-brito/src
      - /usr/src/app/tools/miguel-brito/node_modules

      - ./shared:/usr/src/app/shared
      - /usr/src/app/shared/nestjs/node_modules
      - /usr/src/app/shared/tools/node_modules
